#!/usr/bin/env bash
set -eu

echo "🔵 build"
source hooks/.config

echo "✅ Will build the following architectures: $(IFS=, ; echo "${build_architectures[@]}")"
echo "⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯"

for arch in ${build_architectures[@]}; do

  if [ "${arch}" == "arm" ]
  then
    JELLYFIN_ARCH="armhf"
  else
    JELLYFIN_ARCH=${arch}
  fi

  JELLYFIN_RELEASE=$(curl -k -s "https://api.github.com/repos/jellyfin/jellyfin/releases" | jq -r '.[0] | .tag_name') 
  JELLYFIN_URL=$(curl -k -s "https://api.github.com/repos/jellyfin/jellyfin/releases/tags/${JELLYFIN_RELEASE}" | jq -r '.assets[].browser_download_url' | grep buster_${JELLYFIN_ARCH}.deb)

  JELLYFIN-FFMPEG_RELEASE=$(curl -k -s "https://api.github.com/repos/jellyfin/jellyfin-ffmpeg/releases" | jq -r '.[0] | .tag_name') 
  JELLYFIN-FFMPEG_URL=$(curl -k -s "https://api.github.com/repos/jellyfin/jellyfin-ffmpeg/releases/tags/${JELLYFIN-FFMPEG_RELEASE}" | jq -r '.assets[].browser_download_url' | grep buster_${JELLYFIN_ARCH}.deb)

  echo "✅ building $arch"
  echo "⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯"

  docker exec docker_daemon docker build \
    --squash \
    --platform=${arch} \
    --build-arg BASE_IMAGE_PREFIX=${base_image_prefix_map[${arch}]} \
    --build-arg ARCH=${arch} \
    --file /build/$DOCKERFILE_PATH \
    --tag "${IMAGE_NAME}-${arch}"  \
    /build
done

echo "✅ images built:"
echo "⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯"
docker exec docker_daemon docker image ls

trap "exit 1"          HUP INT PIPE QUIT TERM